org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false


minecraft_version=1.20.1
minecraft_version_range=[1.20.1]

forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=newton
mod_name=Newton
mod_license=MIT
mod_version=1.20.1-1.0.2
mod_group_id=me.kall.newton
mod_authors=Kasualix
mod_description=Newton awoke in the woods and found himself surrounded by apples.

# Proxy
# REMOVE THIS IF YOU WANT TO BUILD THIS PROJECT BY YOURSELF
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7890
